apiVersion: V1
kind: ReplicationController
metadata:
  name: myapp-rc
spec:
  replicas: 3
  selector:
    app: myapp
  template:
    metadata:
      name: myapp-rc
      labels:
        app: myapp-rc
        type: frontend

    spec:
      containers:
        - name: nginx
          image: nginx

