apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
      app: myapp
      type: frontend

spec:
  template:
     metadata:
  name: myapp
  labels:
    name: nginx
    tier: frontend
  spec:
    containers:
    - name: myapp
      image: nginx
replicas: 3
selector: 
    matchLabels:
        type: frontend